apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-server
  name: nginx-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "1"
            limits:
              memory: "128Mi"
              cpu: "1"