apiVersion: v1
Kind: PersistentVolume
metadata:
  labels:
    type: local
  name: pv-02
spec: 
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
  storageClassName: sc-02