apiVersion: v1
kind: Pod
metadata:
  name: meupod01
  labels:
    app: web01
    versao: "01"
spec:
  containers:
    - name: web
      image: nginx
      ports: 
        - name: http 
          containerPort: 80
          protocol: TCP

---

apiVersion: v1
kind: Pod
metadata:
  name: meupod02
  labels:
    app: web01
    versao: "02"
spec:
  containers:
    - name: web
      image: nginx
      ports: 
        - name: http 
          containerPort: 80
          protocol: TCP