name: Avisa sobre a criacao ou tag

on:
  create

jobs:
  print-modification:
    runs-on: ubuntu-latest
    steps:
      - name: Avisa sobre a criacao ou tag
        run: echo "Este workflow foi triggado pois uma regra de branch protection rule foi acionada"