name: Criando o trigger deployment

on:
  deployment

jobs:
  job-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Printa o deployment
        run: Esse job foi triggado por um deployment externo