name: Criando o trigger Pull Request

on:
  pull_request:
    types: [opened, edited, deleted, reopened]
    branches:
      - 'main'
      - 'main*'
      - 'main/**'

jobs:
  job-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Printa o deployment
        run: echo "Uma pull resquest foi aberta"