name: viewing shared files up to the steps

on:
  #push:
  #  branches:
  #    - main
  on:
    workflow_dispatch:

jobs:
  entre-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Check Ubuntu Version
        run: cat /etc/os-release

      - name: Show message
        run: echo "Hello - I am Rafael"
